 version: 2.1
 orbs:
  codecov: codecov/codecov@1.0.4
 jobs:
   one:
     docker:
       - image: circleci/golang:1.12.4
     working_directory: /go/src/github.com/sgoodliff/hello
     steps:
       - checkout
       - run: echo "A first hello"
       - run: sleep 25
       - run: mkdir -p /tmp/test-results
       - restore_cache:
          keys:
            - v1-pkg-cache
       - run: go get github.com/jstemmer/go-junit-report
       - run: go get -v -t -d ./...
       - run: go test -race -coverprofile=/tmp/test-results/coverage.txt -covermode=atomic -v ./...
       - codecov/upload:
          file: /tmp/test-results/coverage.txt
          token: 6bc48cc7-5936-4ecf-abfc-67471579fe58
       - run: go build ./...
       - store_artifacts: # upload test summary for display in Artifacts
          path: /tmp/test-results
          destination: raw-test-output

       - store_test_results: # upload test results for display in Test Summary
          path: /tmp/test-results

       - save_cache:
          key: v1-pkg-cache
          paths:
            - ~/.cache/go-build
   two:
     docker:
       - image: circleci/golang:1.12.4
     working_directory: /go/src/github.com/sgoodliff/hello
     steps:
       - checkout
       - run: echo "A more familiar hi"
       - run: sleep 15
 workflows:
   version: 2
   one_and_two:
     jobs:
       - one
       - two
